//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketProgramming.Data
{
    using System;
    using System.Collections.Generic;
    
    public class Ticket
    {
        public int TicketID { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public string Mail { get; set; }
        public string Ticket1 { get; set; }
        public string Aciklama { get; set; }
        public string IsAktif { get; set; }
        public string Nott { get; set; }
    }
}
